### ISSUE TITLE
Firmware does not reconnect to channel when connection is lost

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-firmware#4]
When loosing connection to the hub, devices running the firmware fail to reconnect to the Hub server on the correct channel.

They reconnect to the *socket*, but do not join the communication channel.

**Comment by t0mhaines** [comment]
Fixed in c428991

**Comment by nelsonic** [comment]
@th0mas fix looks good. 👍 
Is there any way to write a _test_ for this? ✍️ 
So we _know_ it works in the future and nobody accidentally breaks it? 💭

**Comment by t0mhaines** [comment]
This fix just polls the socket until we can reach the server, then re-runs the startup procedure and handshake process. 

I'm not sure how i'd go about testing this, as we'd have to simulate a Hub server failing then starting again.

**Comment by nelsonic** [comment]
Yeah, it's convoluted to test. But sometimes it's _worth_ it because it's a bit of brain-gym! 🧠 
We want our systems to be as fault tolerant / reliable as possible so _forcing_ yourself to think of how to test things is a _really_ good exercise. And it's always an opportunity to learn new things.
For example: I learned that I could have a "mini phoenix" app inside a test:
https://github.com/dwyl/ping/blob/465204a975d93d89f62a45d075903f5a5189aeac/test/ping_test.exs#L17-L35

If you prefer to focus on your next task, that's fine.
Just get into the habit of thinking "_How do I **know** this is working reliably_". (_i.e. always following the [scientific method](https://en.wikipedia.org/wiki/Scientific_method)_)
Having ~~good~~ _complete_ tests is the only way to never get calls at 2am on boxing day because something "broke". 🎁  💩 

**Note**: I'm pretty confident that the fix you have applied in _this_ case works (_for now_...).
I'm just paranoid about writing _any_ code without tests. 🤷‍♂️ 
I once quit a job over exactly this. 👎  (_that was the original impetus for: https://github.com/dwyl/learn-tdd ..._)
The lead dev didn't _want_ to write tests but still expected the team to be responsible for the quality of the code. ROFL! 🤦 
(_I wish I was joking. I'm not. There are still way too many people who think it's "OK" to **never** write tests ..._)
![cowboy-coder](https://camo.githubusercontent.com/3c06516c25db17ca47b4600bc6264a49a3b14533/687474703a2f2f692e696d6775722e636f6d2f4e30567157634c2e706e67)

If you _always_ write tests, you will be able to **`expect`** high quality from everyone you work with. 🥇 
Which means you will be able to work at [highly _interesting_](https://github.com/dwyl/start-here/blob/master/mission.md#a-clear-mission-moon-landing) places like https://www.tesla.com/careers/search#/?department=4
